name: Feature Ticket
description: File a bug report.
labels: ["feature"]
projects: ["CPSC427-2024W-T1/Raycast"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-feature
    attributes:
      label: Description
      description: "What is the desired functionality?"
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: "How will we know when the feature is complete?"
    validations:
      required: true