name: Feature Ticket
description: Add a feature ticket.
labels: ["feature"]
projects: ["CPSC427-2024W-T1/11"]
body:
  - type: textarea
    id: describe-feature
    attributes:
      label: Description
      description: "What is the desired functionality?"
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: "How will we know when the feature is complete?"
    validations:
      required: true